// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import dotenv from "dotenv";
import { Database } from "./types";
dotenv.config();

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
const SUPABASE_PUBLISHABLE_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "";

console.log("yo", SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
